In [2]:
import pandas as pd

df = pd.read_csv("../data_raw/employee_retention.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
# shape: how many rows and columns
df.shape

# quick info about columns and types
df.info()

# basic statistics for numeric columns
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [4]:
df['Attrition'].value_counts()
df['Attrition'].value_counts(normalize=True)

Attrition
No     0.838776
Yes    0.161224
Name: proportion, dtype: float64

In [5]:
# for now, just save as-is
df.to_csv("../data_processed/employee_retention_clean.csv", index=False)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, roc_auc_score

# 1) Separate features and target
X = df.drop(columns=["Attrition"])
y = df["Attrition"].map({"No": 0, "Yes": 1})

X.head(), y.head()

(   Age     BusinessTravel  DailyRate              Department  \
 0   41      Travel_Rarely       1102                   Sales
 1   49  Travel_Frequently        279  Research & Development
 2   37      Travel_Rarely       1373  Research & Development
 3   33  Travel_Frequently       1392  Research & Development
 4   27      Travel_Rarely        591  Research & Development

    DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
 0                 1          2  Life Sciences              1               1
 1                 8          1  Life Sciences              1               2
 2                 2          2          Other              1               4
 3                 3          4  Life Sciences              1               5
 4                 2          1        Medical              1               7

    EnvironmentSatisfaction  ... RelationshipSatisfaction  StandardHours  \
 0                        2  ...                        1             80
 1                        3  ...                        4             80
 2                        4  ...                        2             80
 3                        4  ...                        3             80
 4                        1  ...                        4             80

    StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  WorkLifeBalance  \
 0                 0                  8                     0                1
 1                 1                 10                     3                3
 2                 0                  7                     3                3
 3                 0                  8                     3                3
 4                 1                  6                     3                3

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
 0              6                   4                        0
 1             10                   7                        1
 2              0                   0                        0
 3              8                   7                        3
 4              2                   2                        2

    YearsWithCurrManager
 0                     5
 1                     7
 2                     0
 3                     0
 4                     2

 [5 rows x 34 columns],
 0    1
 1    0
 2    1
 3    0
 4    0
 Name: Attrition, dtype: int64)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((1176, 34), (294, 34))

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, roc_auc_score

# identify categorical and numeric columns
categorical_cols = X.select_dtypes(include=["object", "str"]).columns.tolist()
numeric_cols = X.select_dtypes(exclude=["object", "str"]).columns.tolist()

# one-hot encoder for categoricals
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

preprocess = ColumnTransformer(
    transformers=[
        ("cat", categorical_transformer, categorical_cols),
        ("num", "passthrough", numeric_cols),
    ]
)

# pipeline: preprocessing + model
clf = Pipeline(
    steps=[
        ("preprocess", preprocess),
        ("model", LogisticRegression(max_iter=1000, class_weight="balanced")),
    ]
)

# train
clf.fit(X_train, y_train)

# predict probabilities on test set
y_pred = clf.predict(X_test)
y_proba = clf.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print(classification_report(y_test, y_pred))

ROC-AUC: 0.7387371866655181
              precision    recall  f1-score   support

           0       0.91      0.69      0.79       247
           1       0.29      0.66      0.40        47

    accuracy                           0.69       294
   macro avg       0.60      0.68      0.60       294
weighted avg       0.81      0.69      0.73       294

c:\Users\HP\OneDrive\Documents\people_finance_analytics_platform\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [10]:
import joblib

# save the full pipeline (preprocessing + model)
joblib.dump(clf, "../src/employee_attrition_pipeline.joblib")

['../src/employee_attrition_pipeline.joblib']

In [11]:
import joblib

joblib.dump(clf, "../src/employee_attrition_pipeline.joblib")

['../src/employee_attrition_pipeline.joblib']

In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

test_accuracy = accuracy_score(y_test, y_pred)
test_precision = precision_score(y_test, y_pred)
test_recall = recall_score(y_test, y_pred)
test_f1 = f1_score(y_test, y_pred)
test_roc_auc = roc_auc_score(y_test, y_proba)

print("Accuracy :", round(test_accuracy, 3))
print("Precision:", round(test_precision, 3))
print("Recall   :", round(test_recall, 3))
print("F1-score :", round(test_f1, 3))
print("ROC-AUC  :", round(test_roc_auc, 3))

Accuracy : 0.687
Precision: 0.29
Recall   : 0.66
F1-score : 0.403
ROC-AUC  : 0.739

In [13]:
from sklearn.ensemble import RandomForestClassifier

# random forest model
rf_clf = Pipeline(
    steps=[
        ("preprocess", preprocess),
        ("model", RandomForestClassifier(
            n_estimators=300,
            max_depth=None,
            random_state=42,
            class_weight="balanced",
            n_jobs=-1
        )),
    ]
)

rf_clf.fit(X_train, y_train)

rf_y_pred = rf_clf.predict(X_test)
rf_y_proba = rf_clf.predict_proba(X_test)[:, 1]

print("Random Forest ROC-AUC:", roc_auc_score(y_test, rf_y_proba))
print(classification_report(y_test, rf_y_pred))

Random Forest ROC-AUC: 0.8011025928159187
              precision    recall  f1-score   support

           0       0.85      0.99      0.92       247
           1       0.67      0.09      0.15        47

    accuracy                           0.85       294
   macro avg       0.76      0.54      0.53       294
weighted avg       0.82      0.85      0.79       294

In [16]:
import joblib

# save the trained random forest pipeline
joblib.dump(rf_clf, "models/employee_attrition_random_forest.joblib")

['models/employee_attrition_random_forest.joblib']

In [15]:
import os
import joblib

# create models directory if it doesn't exist
os.makedirs("models", exist_ok=True)

# save the trained random forest pipeline
joblib.dump(rf_clf, "models/employee_attrition_random_forest.joblib")

['models/employee_attrition_random_forest.joblib']

Trained two models to predict employee attrition on the IBM HR Analytics dataset: Logistic Regression and Random Forest. Logistic Regression, combined with one‑hot encoding and class balancing, achieved ROC‑AUC 0.74 and recall 0.66 on the test set, providing a simple and interpretable baseline. Random Forest improved the ranking ability to ROC‑AUC 0.80 and overall accuracy to 0.85, but recall for the minority attrition class remained low (0.09), highlighting the challenge of detecting rare leavers in an imbalanced HR dataset.